{% set name = "colcon-notification" %}
{% set version = "0.2.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 256cd8260762bca8ac7c89f7a9e5a6799c7b12128accf4f8aa0a837edbe0db73

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35 or osx or unix]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - colcon-core >=0.3.7
    - pywin32  # [win]

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide status notifications.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
