{% set name = "colcon-notification" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-notification-{{ version }}.tar.gz
  sha256: 0a188a4debaa103f1fc620babb6f82a90032f01c559090ac51a5ff4cad326550

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1


requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - colcon-core >=0.3.7
    - notify2  # [linux]
    - python
    - pywin32  # [win]

test:
  imports:
    - colcon_notification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to provide status notifications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - ruben-arts
    - Tobias-Fischer
