{% set name = "colcon-notification" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-notification-{{ version }}.tar.gz
  sha256: c45b898073a8e98c4518333b7587f9ea49ac1bc129a7bc4e1390059057031fb8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0


requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - colcon-core >=0.3.7
    - notify2  # [linux]
    - python
    - pywin32  # [win]

test:
  imports:
    - colcon_notification
  commands:   # [python_impl == "cpython"]
    - pip check  # [python_impl == "cpython"]
  requires:   # [python_impl == "cpython"]
    - pip        # [python_impl == "cpython"]

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to provide status notifications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - ruben-arts
    - Tobias-Fischer
