{% set name = "colcon-notification" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-notification-{{ version }}.tar.gz
  sha256: 6aae1ffe73ae956bcb36e330822cd230a2a88c9181b3170aafd1a446638e69b3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: True # [win]

requirements:
  host:
    - pip
    - python
    - stdeb
  run:
    - colcon-core >=0.3.7
    - notify2  # [linux]
    - python
    - pywin32  # [win]

test:
  imports:
    - colcon_notification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to provide status notifications.
  license: Apache-2.0 
  license_file: LICENSE

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - ruben-arts
