{% set name = "colcon-notification" %}
{% set version = "0.2.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5c1bd81ff4e16c5092df8457fec053b19ee01691ff47f44f7fd21170c2d011fe
  patches:
    - pypiwin32.dist.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35 or osx or unix]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - colcon-core >=0.3.7
    - pywin32  # [win]

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide status notifications.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
