{% set name = "colcon-notification" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c295039594812624056369fb85bf8a4a4f2d92666800259b07b112eb3c10ef43

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35 or osx or unix]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - colcon-core >=0.3.7
    - pywin32  # [win]

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide status notifications.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
