context:
  name: colcon-notification
  version: "0.3.3"

package:
  name: colcon-notification
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a97cf4f9cf9ad60a78c3576ea633e50f7c9caae1d4aef57e55bdbb40d21151e0

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - colcon-core >=0.21.3
    - if: linux
      then: notify2
    - python
    - if: win
      then: pywin32

tests:
  - python:
      imports:
        - colcon_notification
      pip_check: false
  - requirements:
      run:
        - if: "python_impl == \"cpython\""
          then: pip
    script:
      - if: "python_impl == \"cpython\""
        then: pip check

about:
  summary: Extension for colcon to provide status notifications.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://colcon.readthedocs.io

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
    - ruben-arts
    - Tobias-Fischer
